/** Application roles — RBAC */
export const ROLES = {
  BUSINESS_OWNER: 'Business Owner',
  WAREHOUSE_WORKER: 'Warehouse Worker',
  STORE_CLERK: 'Store Clerk',
  ACCOUNTANT: 'Accountant',
  INDIVIDUAL_SELLER: 'Individual Seller',
  ADMIN: 'Admin',
  MANAGER: 'Manager',
  VIEWER: 'Viewer'
};

export const ALL_ROLES = Object.values(ROLES);

/** Staff roles inviteable by a business. Platform Admin is never inviteable. */
export const INVITABLE_ROLES = [
  ROLES.STORE_CLERK,
  ROLES.WAREHOUSE_WORKER,
  ROLES.ACCOUNTANT,
  ROLES.MANAGER
];

/** Roles no longer offered or listed in Users & Staff. */
export const HIDDEN_STAFF_ROLES = [ROLES.INDIVIDUAL_SELLER, ROLES.VIEWER, ROLES.ADMIN];

/** Route permission groups */
export const PERMISSIONS = {
  manageBusiness: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ADMIN],

  viewInventory: [
    ROLES.BUSINESS_OWNER,
    ROLES.MANAGER,
    ROLES.ACCOUNTANT,
    ROLES.WAREHOUSE_WORKER,
    ROLES.STORE_CLERK,
    ROLES.INDIVIDUAL_SELLER,
    ROLES.ADMIN,
    ROLES.VIEWER
  ],
  manageInventory: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.WAREHOUSE_WORKER, ROLES.ADMIN],

  viewCost: [
    ROLES.BUSINESS_OWNER,
    ROLES.MANAGER,
    ROLES.WAREHOUSE_WORKER,
    ROLES.ACCOUNTANT,
    ROLES.ADMIN,
    ROLES.VIEWER
  ],

  viewPurchases: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ACCOUNTANT, ROLES.ADMIN, ROLES.VIEWER],
  managePurchases: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ADMIN],

  viewWarehouses: [
    ROLES.BUSINESS_OWNER,
    ROLES.MANAGER,
    ROLES.ACCOUNTANT,
    ROLES.WAREHOUSE_WORKER,
    ROLES.ADMIN,
    ROLES.VIEWER
  ],
  manageWarehouses: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ADMIN],

  viewShipments: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ACCOUNTANT, ROLES.ADMIN, ROLES.VIEWER],
  manageShipments: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ADMIN],

  viewStores: [
    ROLES.BUSINESS_OWNER,
    ROLES.MANAGER,
    ROLES.ACCOUNTANT,
    ROLES.STORE_CLERK,
    ROLES.INDIVIDUAL_SELLER,
    ROLES.ADMIN
  ],
  manageSales: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.STORE_CLERK, ROLES.INDIVIDUAL_SELLER, ROLES.ADMIN],

  viewFinance: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ACCOUNTANT, ROLES.ADMIN],
  manageFinance: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ACCOUNTANT, ROLES.ADMIN],

  manageUsers: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ADMIN],
  viewSettings: [ROLES.BUSINESS_OWNER, ROLES.MANAGER, ROLES.ACCOUNTANT, ROLES.ADMIN]
};
