import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import businessRoutes from './business.routes.js';
import itemRoutes from './item.routes.js';
import warehouseRoutes from './warehouse.routes.js';
import purchaseRoutes from './purchase.routes.js';
import supplierRoutes from './supplier.routes.js';
import shipmentRoutes from './shipment.routes.js';
import shippingRoutes from './shipping.routes.js';
import storeRoutes from './store.routes.js';
import posRoutes from './pos.routes.js';
import financeRoutes from './finance.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import saleRoutes from './sale.routes.js';
import notificationRoutes from './notification.routes.js';
import inventoryRoutes from './inventory.routes.js';
import locationsRoutes from './locations.routes.js';
import uploadRoutes from './upload.routes.js';
import invitationRoutes from './invitation.routes.js';
import subscriptionRoutes from './subscription.routes.js';
import stripeRoutes from './stripe.routes.js';
import legacyRoutes from './legacy.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/businesses', businessRoutes);
router.use('/items', itemRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/shipments', shipmentRoutes);
router.use('/shipping', shippingRoutes);
router.use('/stores', storeRoutes);
router.use('/pos', posRoutes);
router.use('/finance', financeRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/sales', saleRoutes);
router.use('/notifications', notificationRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/locations', locationsRoutes);
router.use('/uploads', uploadRoutes);
router.use('/invitations', invitationRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/stripe', stripeRoutes);
router.use('/', legacyRoutes);

export default router;
