import JSZip from 'jszip';
import { shippingApi } from '../services/shippingApi';

function csvEscape(value) {
  const s = value == null ? '' : String(value);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function downloadTextFile(filename, content, mime = 'text/csv;charset=utf-8') {
  downloadBlob(filename, new Blob([content], { type: mime }));
}

function stamp() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function safeFilePart(value, fallback = 'document') {
  const cleaned = String(value || fallback)
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, '-')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return cleaned.slice(0, 80) || fallback;
}

function filenameFromDisposition(header, fallback) {
  if (!header) return fallback;
  const utf = header.match(/filename\*=UTF-8''([^;]+)/i);
  if (utf?.[1]) {
    try {
      return decodeURIComponent(utf[1]);
    } catch {
      /* fall through */
    }
  }
  const plain = header.match(/filename="?([^";]+)"?/i);
  return plain?.[1] || fallback;
}

function documentsToCsv(rows = []) {
  const headers = [
    'Document ID',
    'Name',
    'Type',
    'Shipment ID',
    'Route',
    'Status',
    'File Name',
    'File Size',
    'Uploaded',
    'Notes',
    'File URL'
  ];
  const lines = [headers.map(csvEscape).join(',')];
  rows.forEach((d) => {
    lines.push(
      [
        d.docId || d.id || '',
        d.name || '',
        d.typeLabel || d.type || '',
        d.shipmentId || '',
        d.route || '',
        d.statusLabel || d.status || '',
        d.fileName || '',
        d.fileSize || '',
        d.uploaded || '',
        d.notes || '',
        d.fileUrl || ''
      ]
        .map(csvEscape)
        .join(',')
    );
  });
  return `\uFEFF${lines.join('\r\n')}`;
}

function openPrintWindow(title, bodyHtml) {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: Segoe UI, Arial, sans-serif; color: #1a2b3c; margin: 24px; }
    h1 { font-size: 20px; margin: 0 0 4px; color: #1A3C5E; }
    .sub { color: #8A97A8; font-size: 12px; margin-bottom: 18px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th, td { border: 1px solid #E5EAF0; padding: 8px 10px; text-align: left; }
    th { background: #FAFBFC; color: #8A97A8; text-transform: uppercase; font-size: 10px; letter-spacing: 0.4px; }
    .kpi { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 16px; }
    .kpi div { background: #F4F7FA; border-radius: 8px; padding: 10px 14px; min-width: 120px; }
    .kpi strong { display: block; font-size: 18px; color: #1A3C5E; }
    .kpi span { font-size: 11px; color: #8A97A8; }
    @media print { body { margin: 12px; } }
  </style>
</head>
<body>
  ${bodyHtml}
  <script>
    window.addEventListener('load', function () {
      setTimeout(function () { window.focus(); window.print(); }, 250);
    });
  </script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank', 'width=900,height=700');
  if (!win) {
    URL.revokeObjectURL(url);
    return false;
  }
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
  return true;
}

function docSummaryText(doc) {
  return [
    `Document: ${doc.name || ''}`,
    `ID: ${doc.docId || doc.id || ''}`,
    `Type: ${doc.typeLabel || doc.type || ''}`,
    `Shipment: ${doc.shipmentId || ''}`,
    `Route: ${doc.route || ''}`,
    `Status: ${doc.statusLabel || doc.status || ''}`,
    `File: ${doc.fileName || '—'} (${doc.fileSize || '—'})`,
    `Uploaded: ${doc.uploaded || '—'}`,
    `URL: ${doc.fileUrl || '—'}`,
    `Notes: ${doc.notes || '—'}`,
    '',
    'Generated by CargoTrader'
  ].join('\n');
}

/** Fetch document bytes via authenticated API proxy (avoids Cloudinary CORS). */
async function fetchDocBlob(doc) {
  const id = doc?.docId || doc?.id;
  if (!id) return null;
  try {
    const res = await shippingApi.downloadDocument(id);
    const blob = res.data;
    if (!(blob instanceof Blob) || blob.size === 0) return null;
    if (blob.type && blob.type.includes('application/json')) {
      const text = await blob.text();
      try {
        const parsed = JSON.parse(text);
        if (parsed?.message) throw new Error(parsed.message);
      } catch (e) {
        if (e.message && !e.message.includes('JSON')) throw e;
      }
      return null;
    }
    const headerName = filenameFromDisposition(
      res.headers?.['content-disposition'],
      doc.fileName || doc.name || id
    );
    return { blob, fileName: headerName };
  } catch {
    if (!doc?.fileUrl) return null;
    try {
      const res = await fetch(doc.fileUrl);
      if (!res.ok) return null;
      const blob = await res.blob();
      return { blob, fileName: doc.fileName || doc.name || id };
    } catch {
      return null;
    }
  }
}

/** Export document metadata as Excel-compatible CSV. */
export function exportDocumentsCsv(rows = [], { filename } = {}) {
  if (!rows.length) return false;
  downloadTextFile(filename || `shipment-documents-${stamp()}.csv`, documentsToCsv(rows));
  return true;
}

/** Print a documents list report. */
export function printDocumentsReport(rows = [], { title = 'Shipment Documents' } = {}) {
  if (!rows.length) return false;
  const bodyRows = rows
    .map(
      (d) => `<tr>
        <td>${escapeHtml(d.name || '')}</td>
        <td>${escapeHtml(d.typeLabel || d.type || '')}</td>
        <td>${escapeHtml(d.shipmentId || '')}</td>
        <td>${escapeHtml(d.route || '')}</td>
        <td>${escapeHtml(d.statusLabel || d.status || '')}</td>
        <td>${escapeHtml(d.uploaded || '')}</td>
        <td>${escapeHtml(d.fileName || '')}</td>
      </tr>`
    )
    .join('');

  return openPrintWindow(
    title,
    `<h1>${escapeHtml(title)}</h1>
     <p class="sub">Generated ${new Date().toLocaleString()} · CargoTrader · ${rows.length} document${rows.length !== 1 ? 's' : ''}</p>
     <div class="kpi">
       <div><strong>${rows.length}</strong><span>Documents</span></div>
     </div>
     <table>
       <thead>
         <tr>
           <th>Document</th>
           <th>Type</th>
           <th>Shipment</th>
           <th>Route</th>
           <th>Status</th>
           <th>Uploaded</th>
           <th>File</th>
         </tr>
       </thead>
       <tbody>${bodyRows}</tbody>
     </table>`
  );
}

/** Download a single document file (returns false if only a text summary was saved). */
export async function downloadDocumentFile(doc) {
  if (!doc) return false;
  const fetched = await fetchDocBlob(doc);
  if (fetched?.blob) {
    const name = safeFilePart(fetched.fileName || doc.fileName || doc.name || doc.docId, 'document');
    downloadBlob(name.includes('.') ? name : `${name}.bin`, fetched.blob);
    return true;
  }
  const base = safeFilePart(doc.fileName || doc.name || doc.docId, 'document');
  downloadTextFile(
    base.endsWith('.txt') ? base : `${base.replace(/\.[^.]+$/, '') || base}.txt`,
    docSummaryText(doc),
    'text/plain;charset=utf-8'
  );
  return false;
}

/**
 * Build and download a ZIP of documents.
 * Includes a CSV manifest plus each file (or a .txt summary when no file URL).
 */
export async function exportDocumentsZip(rows = [], { filename } = {}) {
  if (!rows.length) return false;

  const zip = new JSZip();
  zip.file('documents-manifest.csv', documentsToCsv(rows));

  const usedNames = new Set(['documents-manifest.csv']);
  for (let i = 0; i < rows.length; i += 1) {
    const doc = rows[i];
    const idPart = safeFilePart(doc.docId || doc.id || `doc-${i + 1}`, `doc-${i + 1}`);
    const preferred = safeFilePart(doc.fileName || doc.name || idPart, idPart);
    let entryName = preferred.includes('.') ? preferred : `${preferred}.txt`;
    if (usedNames.has(entryName.toLowerCase())) {
      const ext = entryName.includes('.') ? entryName.slice(entryName.lastIndexOf('.')) : '.txt';
      const stem = entryName.includes('.') ? entryName.slice(0, entryName.lastIndexOf('.')) : entryName;
      entryName = `${stem}-${idPart}${ext}`;
    }
    usedNames.add(entryName.toLowerCase());

    const fetched = await fetchDocBlob(doc);
    if (fetched?.blob) {
      zip.file(entryName, fetched.blob);
    } else {
      const txtName = entryName.endsWith('.txt') ? entryName : `${entryName}.txt`;
      zip.file(txtName, docSummaryText(doc));
    }
  }

  const zipBlob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(filename || `shipment-documents-${stamp()}.zip`, zipBlob);
  return true;
}

/** Open document in a new tab via authenticated blob URL (PDF/images). */
export async function openDocumentInNewTab(doc) {
  const fetched = await fetchDocBlob(doc);
  if (!fetched?.blob) return false;
  const url = URL.createObjectURL(fetched.blob);
  const win = window.open(url, '_blank', 'noopener,noreferrer');
  if (!win) {
    URL.revokeObjectURL(url);
    return false;
  }
  setTimeout(() => URL.revokeObjectURL(url), 120_000);
  return true;
}
